Больше деталей
htmlacademy-javascript/1061909-keksobooking-22 pull request #3
Opened 2021-02-08 17:37 UTC by Akimba-png

2021-02-09 16:45 UTC, Dima-Dim requested changes

2021-02-09 16:45 UTC, Dima-Dim commented on js/main.js
> +  const RandomArray = [];
https://up.htmlacademy.ru/javascript/22/criteries#b3
`RandomArray` -> `randomArray`

2021-02-09 16:45 UTC, Dima-Dim commented on js/main.js
> +  const locationX = getRandomPoint(35.65000, 35.70000, 6);
`35.65000, 35.70000, 6` - магические цифры.

2021-02-09 18:40 UTC, Akimba-png commented on js/main.js
> +  const RandomArray = [];
Поправил. Кстати, а если это массив, не нужно ли его было во множественном числе объявлять?

2021-02-10 07:54 UTC, Dima-Dim commented on js/main.js
> +  const RandomArray = [];
Что могло бы быть во множестенном числе? :) Это ведь один Array. Если бы ты написал что в нём будет, тогда да, это что-то нужно было бы написать во множественном числе.

2021-02-11 07:16 UTC, merged